backend:
  name: git-gateway
  branch: master

media_folder: source/images/uploads
public_folder: /images/uploads

#publish_mode: editorial_workflow #optional, enables publishing workflow

collections:
  - name: blog
    label: Blog
    folder: source/posts/
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Description, name: description, widget: text}
      - {label: Body, name: body, widget: markdown}

  - name: pages
    label: Pages
    files:
      - file: data/pages/about.yml
        label: About
        name: about
        fields:
          - {label: Title, name: title, widget: string}
          - label: Unique selling points
            name: usps
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Description, name: description, widget: string}

      - file: "data/pages/home.yml"
        label: Homepage
        name: home
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}

  - name: settings
    label: Settings
    files:
      - file: data/settings/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Navigation items
            name: nav_items
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}

