backend:
  name: git-gateway
  branch: master

media_folder: source/images/uploads
public_folder: /images/uploads

#publish_mode: editorial_workflow #optional, enables publishing workflow

collections:
  #markdown middleman blog example
  - name: blog
    label: Blog
    folder: source/posts/
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Description, name: description, widget: text}
      - {label: Body, name: body, widget: markdown}

  #yaml middleman data example
  - name: products
    label: Products
    folder: data/products/
    create: true
    slug: '{{title}}'
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Image, name: image, widget: image}

      - label: Weight
        name: weight
        widget: object
        fields:
          - {label: Amount, name: amount, widget: number}
          - {label: Unit, name: unit, widget: select, options: ['kg', 'pound', 'stone'], default: 'kg'}

      - {label: Price, name: price, widget: number}
      - {label: Body, name: body, widget: markdown}

  - name: pages
    label: Pages
    files:
      - file: "data/pages/home.yml"
        label: Homepage
        name: home
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
          - label: Story
            name: story
            widget: markdown

  - name: settings
    label: Settings
    files:
      - file: data/settings/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Navigation items
            name: nav_items
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}

