backend:
  name: git-gateway
  branch: master

media_folder: source/images
public_folder: /images

#publish_mode: editorial_workflow #optional, enables publishing workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "source/posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "data/pages/about.yml"
        label: "About"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: string}
          - label: "Values"
            name: "values"
            widget: "list"
            fields:
              - {label: Value name, name: value_name, widget: string}
              - {label: Value description, name: value_description, widget: string}